name: UPSC MCQ Daily Post by AI

on:
  schedule:
    - cron: "0 4 * * *"   # 9:30 AM IST
  workflow_dispatch:

jobs:
  mcq_post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install transformers torch requests

    - name: Generate & Post MCQ
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python generate_and_post_mcq.py
